fpparms = ('HP', 'Unknown - Slope', 'Horiz model damage scale', 'Vert model damage scale',
'Model damage scale time', 'Unknown - Weight', 'Move Speed', 'N/A Unused',
'Rotation acceleration', 'Following radius', 'Resting radius', 'Renotice radius',
'Sight radius', 'FOV', 'Exploration radius', 'Exploration angle', 'Shake rate',
'Shake knockback', 'Shake damage', 'Shake range', 'Shock attack max range',
'Shock attack max angle', 'Attack hit range', 'Attack hit angle', 'Attack damage',
'Height visibility', 'Exploration height', 'HP wheel height', 'Rotation speed',
'Warning time', 'Unknown', 'Regeneration rate', 'Off-camera radius', 'Collision radius',
'Being damaged radius', 'Petrify duration', 'Purple drop damage', 'Purple stun chance',
'Purple stun time') # only the general fp parameters

sparms = ('Friction', 'wallReflection', 'faceDirAdjust', 'Acceleration',
'Bounce') # only the (mostly unchanged over enemies) s parameters

badenemies = ('chiyogami', 'clover', 'daiodored', 'daiodogreen', 'hikarikinoko',
'jigumohouse', 'kareooinu_l', 'kareooinu_s', 'magaret', 'nekojarashi', 'ooinu_l',
'ooinu_s', 'panhouse', 'tanpopo', 'tukushi', 'tyre', 'wakami_l', 'wakami_s',
'watage', 'zenmai') # the entities that really shouldn't have their parms edited

enemynames = {'armor':'Cloaking Burrow-Nit', 'baby':'Bulborb Larva',
'bigfoot':'Raging Long-Legs', 'bigtreasure':'Titan Dweevil', 'blackman':'Waterwraith',
'bluechappy':'Orange Bulborb', 'bluekochappy':'Dwarf Orange Bulborb', 'bomb':'Bomb-rock',
'bombotakara':'Volatile Dweevil', 'bombsarai':'Careening Dirigibug', 'catfish':'Water Dumple',
'chappy':'Red Bulborb', 'damagumo':'Beady Long Legs', 'dangomushi':'Segmented Crawbster',
'demon':'Bumbling Snitchbug', 'egg':'Egg', 'elecbug':'Anode Beetle', 'elechiba':'Electrical wire',
'elecotakara':'Anode Dweevil', 'fart':'Doodlebug', 'firechappy':'Fiery Bulblax',
'fkabuto':'Buried Beetle Larva', 'fminihoudai':'Buried Gatling Groink', 'frog':'Yellow Wollywog',
'fuefuki':'Antenna Beetle', 'gashiba':'Gas pipe', 'gasotakara':'Munge Dweevil',
'hana':'Creeping Chrysanthemum', 'hanachirashi':'Withering Blowhog', 'hiba':'Fire geyser',
'houdai':'Man-at-Legs', 'imomushi':'Ravenous Whiskerpillar', 'jigumo':'Hermit Crawmad',
'kabuto':'Beetle Larva', 'kingchappy':'Emperor Bulblax', 'kochappy':'Dwarf Red Bulborb',
'kogane':'Flint Beetle', 'kumachappy':'Spotty Bulbear', 'kumakochappy':'Dwarf Bulbear',
'kurage':'Lesser Spotted Jellyfloat', 'leafchappy':'Bulbmin', 'mar':'Puffy Blowhog',
'marofrog':'Wollywog', 'minihoudai':'Gatling Groink', 'miulin':'Mamuta',
'onikurage':'Greater Spotted Jellyfloat', 'oopanmodoki':'Giant Breadbug',
'panmodoki':'Breadbug', 'pelplant':'Pellet Posy', 'pom':'Candypop Bud', 'queen':'Empress Bulblax',
'qurione':'Honeywisp', 'rkabuto':'Decorated Cannon Beetle', 'rock':'Boulder',
'sarai':'Swooping Snitchbug', 'shijimichou':'Unmarked Spectralid', 'snakecrow':'Burrowing Snagret',
'snakewhole':'Pileated Snagret', 'sokkuri':'Skitter Leaf', 'stone':'Beetle boulder',
'tadpole':'Wogpole', 'tamagomushi':'Mitite', 'tank':'Fiery Blowhog', 'tobi':'Shearwig',
'ujia':'Female Sheargrub', 'ujib':'Male Sheargrub', 'umimushi':'Bloyster',
'waterotakara':'Caustic Dweevil', 'wealthy':'Glint Beetle', 'wtank':'Watery Blowhog',
'yellowchappy':'Hairy Bulborb', 'yellowkochappy':'Snow Bulborb'}
